linad: linad.cpp boost_1_57_0
	g++ linad.cpp -o linad -I boost_1_57_0 -lz -lrt -lpthread

boost_1_57_0:
	wget "http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.gz"
	tar xvzf boost_1_57_0.tar.gz
	rm boost_1_57_0.tar.gz
